const colors={technology:'#2467ea',policy:'#2f9e62',industry:'#7a52e8',institution:'#f27a22'};
const labels={technology:'기술',policy:'정책',industry:'산업',institution:'제도'};
const fmt=v=>typeof v==='number'?v.toLocaleString('ko-KR'):v;
let DATA, indicatorData=[];
async function loadData(){const r=await fetch('data/dashboard.json',{cache:'no-store'});if(!r.ok)throw new Error('데이터를 불러오지 못했습니다.');return r.json()}
function spark(id,values,color){new Chart(document.getElementById(id),{type:'line',data:{labels:values.map((_,i)=>i),datasets:[{data:values,borderColor:color,borderWidth:2,pointRadius:0,tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{enabled:false}},scales:{x:{display:false},y:{display:false}}}})}
function renderSummary(items){summaryCards.innerHTML=items.map((x,i)=>`<article class="summary-card"><div class="type" style="color:${colors[x.type]}">${x.typeLabel}</div><div class="label">${x.label}</div><div class="value">${fmt(x.value)} <small>${x.unit}</small></div><div class="delta">▲ ${x.delta}</div><div class="sparkline"><canvas id="spark${i}"></canvas></div></article>`).join('');items.forEach((x,i)=>spark(`spark${i}`,x.trend,colors[x.type]))}
function renderSimple(id,items,fn){document.getElementById(id).innerHTML=items.map(fn).join('')}
function renderValueChain(items){renderSimple('valueChain',items,x=>`<article class="value-step" style="color:${colors[x.type]}"><h3>${x.title}<small>${x.subtitle}</small></h3><p>${x.lines.join('<br>')}</p><button data-type="${x.type}">자세히 보기</button></article>`)}
function basicLineChart(id,labels,values,color,unit){new Chart(document.getElementById(id),{type:'line',data:{labels,datasets:[{data:values,borderColor:color,backgroundColor:`${color}18`,tension:.3,pointRadius:3,fill:true}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${fmt(c.raw)} ${unit}`}}},scales:{x:{grid:{display:false}},y:{grid:{color:'#edf1f5'}}}})}
function barChart(id,labels,values,color,unit){new Chart(document.getElementById(id),{type:'bar',data:{labels,datasets:[{data:values,backgroundColor:labels.map((_,i)=>i===0?color:'#d6dbe3'),borderRadius:4}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>`${fmt(c.raw)} ${unit}`}}},scales:{x:{grid:{display:false}},y:{beginAtZero:true,grid:{color:'#edf1f5'}}}})}
function renderIndicators(){const q=indicatorSearch.value.trim().toLowerCase(),c=indicatorCategory.value;const rows=indicatorData.filter(x=>(c==='all'||x.category===c)&&(!q||`${x.category} ${x.title} ${x.question}`.toLowerCase().includes(q)));indicatorTable.innerHTML=rows.map(x=>`<tr><td><span class="area-pill">${x.category}</span></td><td>${x.no}</td><td>${x.title}</td><td>${x.graph?'O':'-'}</td><td>${x.question||''}</td></tr>`).join('')}
function renderTopic(name){const t=DATA.topics[name];topicTags.innerHTML=t.keywords.map(k=>`<span>${k}</span>`).join('');topicMatrix.innerHTML=['technology','policy','industry','institution'].map(type=>`<article class="topic-card ${type}"><div class="topic-card-head"><b>${labels[type]}</b><span>${t[type].headline}</span></div><ul>${t[type].items.map(x=>`<li>${x}</li>`).join('')}</ul><button>관련 자료 보기</button></article>`).join('')}
function renderCountry(){const a=DATA.countries[countryA.value],b=DATA.countries[countryB.value];countryCards.innerHTML=['technology','policy','industry','institution'].map(type=>`<article class="compare-card"><h3 style="color:${colors[type]}">${labels[type]}</h3><div class="compare-column"><b>${countryA.value}</b><p>${a[type]}</p></div><div class="compare-column"><b>${countryB.value}</b><p>${b[type]}</p></div></article>`).join('')}
async function init(){DATA=await loadData();baseDate.textContent=DATA.baseDate;renderSummary(DATA.summary);renderSimple('issuesList',DATA.issues,x=>`<div class="issue-item"><span class="tag ${x.level}">${x.levelLabel}</span><span>${x.title}</span><b>${x.days}</b></div>`);renderValueChain(DATA.valueChain);renderSimple('scheduleList',DATA.schedule,x=>`<div class="schedule-item"><time>${x.date}</time><span>${x.title}</span></div>`);['technology','policy','industry','institution'].forEach(type=>renderSimple(type==='technology'?'techUpdates':type==='policy'?'policyUpdates':type==='industry'?'industryUpdates':'institutionUpdates',DATA.updates[type],x=>`<div class="update-item"><span class="update-kind">${x.kind}</span><span>${x.title}</span><time>${x.date}</time></div>`));renderSimple('archiveList',DATA.archive,x=>`<div class="document-item"><span class="document-type">${x.type}</span><span>${x.title}</span><time>${x.date}</time></div>`);renderSimple('sourceCards',DATA.sources,x=>`<div class="source-card"><strong>${x.name}</strong><span>${x.state}</span></div>`);barChart('techChart',DATA.charts.technology.labels,DATA.charts.technology.values,colors.technology,'%');basicLineChart('policyChart',DATA.charts.policy.labels,DATA.charts.policy.values,colors.policy,'조원');basicLineChart('industryChart',DATA.charts.industry.labels,DATA.charts.industry.values,colors.industry,'조원');basicLineChart('peopleChart',DATA.charts.people.labels,DATA.charts.people.values,colors.policy,'명');indicatorData=DATA.indicators;indicatorCategory.innerHTML='<option value="all">전체</option>'+[...new Set(indicatorData.map(x=>x.category))].map(x=>`<option>${x}</option>`).join('');renderIndicators();topicSelect.innerHTML=Object.keys(DATA.topics).map(x=>`<option>${x}</option>`).join('');renderTopic(topicSelect.value);const cs=Object.keys(DATA.countries);countryA.innerHTML=cs.map(x=>`<option>${x}</option>`).join('');countryB.innerHTML=cs.map((x,i)=>`<option ${i===1?'selected':''}>${x}</option>`).join('');renderCountry()}
document.addEventListener('DOMContentLoaded',()=>{init().catch(e=>alert(e.message));indicatorSearch.addEventListener('input',renderIndicators);indicatorCategory.addEventListener('change',renderIndicators);topicSelect.addEventListener('change',e=>renderTopic(e.target.value));countryA.addEventListener('change',renderCountry);countryB.addEventListener('change',renderCountry);mobileMenu.addEventListener('click',()=>sidebar.classList.toggle('open'));document.querySelectorAll('.nav-link').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));a.classList.add('active');sidebar.classList.remove('open')}));document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));aiForm.addEventListener('submit',e=>{e.preventDefault();const q=aiInput.value.trim();aiAnswer.innerHTML=q?`<b>데모 응답</b><br>“${q}”를 기술·정책·산업·제도 4개 영역으로 분류하고, 관련 지표·보고서·법령을 함께 제시하도록 설계할 수 있습니다. 실제 답변 생성에는 문서검색과 AI 백엔드 연결이 필요합니다.`:'질문을 입력해 주세요.'})});
